### ISSUE TITLE
I am using a cluster installed by kubeadm, can I use this project

### ISSUE THREAD

**Issue by kubecto** [snapp-incubator/ceph-s3-operator#36]
When I went to create the user, I reported an error that was not recognized by the api

```
createuser.yaml
apiVersion: s3.snappcloud.io/v1alpha1
kind: S3UserClaim
metadata:
  name: s3userclaim-sample
  namespace: s3-operator-test
spec:
  s3UserClass: ceph-dashboard
  readonlySecret: s3-sample-readonly-secret
  adminSecret: s3-sampdashboardn-secret
  subusers:
    - subuser1
    - subuser2
```

```
2024-02-29T07:36:12Z	ERROR	s3userclaim-resource	failed to validate against cluster quota	{"error": "failed to get clusterQuota, no matches for kind \"ClusterResourceQuota\" in version \"quota.openshift.io/v1\""}
```
